server:
  port: 7000
eureka:
  instance:
    hostname: localhost #eureka服务端的实例名称
  client:
    register-with-eureka: false #false表示不向注册中心注册自己。
    fetch-registry: false       #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://www.eureka9001.com:7001/eureka,http://www.eureka9002.com:7002/eureka
      #http://www.eureka9001.com:7001/eureka,http://www.eureka9002.com:7002/eureka
      #http://localhost:7001/eureka,http://localhost:7002/eureka
