server:
  port: 80
eureka:
  client:
    register-with-eureka: false #当前是微服务的调用端、消费端，不进行注册
    service-url:
      defaultZone: http://www.eureka9000.com:7000/eureka,http://www.eureka9001.com:7001/eureka,http://www.eureka9002.com:7002/eureka
      #http://localhost:7000/eureka,http://localhost:7001/eureka,http://localhost:7002/eureka
      #http://www.eureka7000.com:7000/eureka,http://www.eureka7001.com:7001/eureka,http://www.eureka7002.com:7002/eureka

#Hystrix降级机制的相关配置
feign:
  hystrix:
    enabled: true
